version: "3"
services:
  database:
    image: postgres:12.2
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: convomark
      POSTGRES_PASSWORD: convomark
      POSTGRES_DB: convomark_development
    volumes:
    - "convomarkbot_db:/var/lib/postgresql/data"
  redis:
    image: redis:5
    ports:
    - "6379:6379"

volumes:
  convomarkbot_db:
